import { z } from "zod";
import { LruCache } from "@/lib/cache/lru";
import { INDIACODE_BASE_URL } from "@/lib/statute/urls";

/**
 * Read-only client for the IndiaCode open API, which serves the text of
 * Indian central and state legislation. Every statute the app shows is fetched
 * from here and linked, so nothing about the law is generated by a model.
 *
 * The API needs no key, sets open CORS and asks only that bulk harvesting be
 * done from its CSV exports rather than pagination.
 */

export { INDIACODE_BASE_URL };

/** Only links back to the API's own host are ever rendered; anything else is dropped. */
export function isIndiaCodeUrl(value: string): boolean {
  try {
    const url = new URL(value);
    return url.protocol === "https:" && url.host === new URL(INDIACODE_BASE_URL).host;
  } catch {
    return false;
  }
}

const indiaCodeUrl = z.string().refine(isIndiaCodeUrl, "not an IndiaCode link");
const REQUEST_TIMEOUT_MS = 6_000;
/** A search page or one section; anything larger is not what the API serves. */
const MAX_RESPONSE_BYTES = 1024 * 1024;
const CACHE_ENTRIES = 300;
const CACHE_TTL_MS = 60 * 60 * 1000;

const searchHitSchema = z.object({
  kind: z.string(),
  ref: z.string(),
  title: z.string(),
  act: z.string().optional(),
  snippet: z.string().optional(),
  url: indiaCodeUrl,
});

const searchResponseSchema = z.object({
  total: z.number(),
  results: z.array(searchHitSchema),
});

const sectionResponseSchema = z.object({
  act: z.object({
    id: z.string(),
    short_title: z.string(),
    in_force: z.boolean().optional(),
    url: indiaCodeUrl,
  }),
  section: z.object({
    number: z.string(),
    heading: z.string().nullable().optional(),
    text: z.string(),
    url: indiaCodeUrl.optional(),
  }),
});

export interface StatuteHit {
  ref: string;
  title: string;
  act: string;
  snippet: string;
  url: string;
}

export interface StatuteSection {
  actId: string;
  actTitle: string;
  inForce: boolean;
  number: string;
  heading: string | null;
  text: string;
  url: string;
}

export type FetchLike = (input: string, init?: RequestInit) => Promise<Response>;

export interface IndiaCodeClient {
  search(query: string, limit?: number): Promise<StatuteHit[]>;
  getSection(actId: string, number: string): Promise<StatuteSection | null>;
}

/**
 * Fetch one JSON document with a deadline and a size cap. The error carries the
 * status only: the URL holds the search phrase, which is derived from the
 * document and must not reach the logs.
 */
async function fetchJson(fetchImpl: FetchLike, url: string): Promise<unknown> {
  const response = await fetchImpl(url, {
    headers: { accept: "application/json" },
    signal: AbortSignal.timeout(REQUEST_TIMEOUT_MS),
  });
  if (!response.ok) throw new Error(`IndiaCode responded ${response.status}`);
  const declared = Number(response.headers.get("content-length") ?? 0);
  if (declared > MAX_RESPONSE_BYTES) throw new Error("IndiaCode response too large");
  const body = await response.text();
  if (body.length > MAX_RESPONSE_BYTES) throw new Error("IndiaCode response too large");
  return JSON.parse(body);
}

function toHit(raw: z.infer<typeof searchHitSchema>): StatuteHit {
  return {
    ref: raw.ref,
    title: raw.title,
    act: raw.act ?? raw.title,
    snippet: raw.snippet ?? "",
    url: raw.url,
  };
}

/** Create a client. `fetchImpl` is injectable so tests never touch the network. */
export function createIndiaCodeClient(fetchImpl: FetchLike = fetch): IndiaCodeClient {
  const searchCache = new LruCache<StatuteHit[]>(CACHE_ENTRIES, CACHE_TTL_MS);
  const sectionCache = new LruCache<StatuteSection | null>(CACHE_ENTRIES, CACHE_TTL_MS);

  return {
    async search(query, limit = 3) {
      const key = `${limit}:${query.trim().toLowerCase()}`;
      const cached = searchCache.get(key);
      if (cached) return cached;
      const params = new URLSearchParams({
        q: query.trim(),
        kind: "section",
        limit: String(limit),
      });
      const parsed = searchResponseSchema.safeParse(
        await fetchJson(fetchImpl, `${INDIACODE_BASE_URL}/api/v1/search?${params}`),
      );
      const hits = parsed.success ? parsed.data.results.map(toHit) : [];
      searchCache.set(key, hits);
      return hits;
    },

    async getSection(actId, number) {
      const key = `${actId}/${number}`;
      const cached = sectionCache.get(key);
      if (cached !== undefined) return cached;
      const url = `${INDIACODE_BASE_URL}/api/v1/${encodeURIComponent(actId)}/section/${encodeURIComponent(number)}`;
      const parsed = sectionResponseSchema.safeParse(await fetchJson(fetchImpl, url));
      const section = parsed.success ? toSection(parsed.data) : null;
      sectionCache.set(key, section);
      return section;
    },
  };
}

function toSection(data: z.infer<typeof sectionResponseSchema>): StatuteSection {
  return {
    actId: data.act.id,
    actTitle: data.act.short_title,
    inForce: data.act.in_force ?? true,
    number: data.section.number,
    heading: data.section.heading ?? null,
    text: data.section.text,
    url: data.section.url ?? `${data.act.url}section/${data.section.number}/`,
  };
}

/** Parse a `ref` such as `contract-act/73` into its act id and section number. */
export function parseStatuteRef(ref: string): { actId: string; number: string } | null {
  const slash = ref.lastIndexOf("/");
  if (slash <= 0 || slash === ref.length - 1) return null;
  return { actId: ref.slice(0, slash), number: ref.slice(slash + 1) };
}
